runtime: nodejs16 # or another supported version
env_variables:
  DB_HOST: 34.138.7.8
  DB_NAME: nucleadb
  DB_USER: nuclea
  DB_PASSWORD: Nuclea2023
  DB_PORT: 5432
  API_KEY: "OhWZwy+E7rqmKRx4REUcJw==Hh5WL7BxiKwNKai4"
  
default_expiration: "4d 5h"